#!/usr/bin/env python3
"""
Append animation frame 1 variants to the obstacle atlas.

Row 0 (y=0..49):  original 8 tiles — untouched.
Row 1 (y=50..91): frame 1 for animated tiles at their same x positions.

  red_arrow_f1  (x=255, y=50, 40x33): sprite shifted 2px right → judder hints motion
  red_spike_f1  (x=297, y=50, 59x42): sprite shifted 2px up   → spikes "lunge"
  gold_block_f1 (x=487, y=50, 58x39): sprite shifted 1px diag  → gleam bounce

Re-run this script any time the base atlas row is updated. It reads the existing
public/assets/obstacles.png so it works whether the file was just regenerated by
build-obstacles.py or was already extended.

Usage: python3 scripts/gen-anim-frames.py
"""
from PIL import Image

ATLAS = "public/assets/obstacles.png"
ROW0_H = 50   # height reserved for the base tile row
ROW1_H = 42   # max height for animation row (red_spike / purple_pillar height)


def shift_right(tile: Image.Image, px: int) -> Image.Image:
    w, h = tile.size
    out = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    out.paste(tile.crop((0, 0, w - px, h)), (px, 0))
    return out


def shift_up(tile: Image.Image, px: int) -> Image.Image:
    w, h = tile.size
    out = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    out.paste(tile.crop((0, px, w, h)), (0, 0))
    return out


def shift_diag(tile: Image.Image, dx: int, dy: int) -> Image.Image:
    """Shift content dx right and dy up, clipping at edges."""
    w, h = tile.size
    out = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    src_x0, src_y0 = max(0, -dx), max(0, dy)
    src_x1, src_y1 = min(w, w - dx), min(h, h + dy)
    dst_x, dst_y = max(0, dx), max(0, -dy)
    out.paste(tile.crop((src_x0, src_y0, src_x1, src_y1)), (dst_x, dst_y))
    return out


def main() -> None:
    # Always rebuild from a clean copy of row 0 so re-runs are idempotent.
    full = Image.open(ATLAS).convert("RGBA")
    bw = full.size[0]
    base = full.crop((0, 0, bw, ROW0_H))

    new_h = ROW0_H + ROW1_H
    atlas = Image.new("RGBA", (bw, new_h), (0, 0, 0, 0))
    atlas.paste(base, (0, 0))

    # red_arrow_f1: x=255, y=0, w=40, h=33 — shift 2px right
    arrow = base.crop((255, 0, 255 + 40, 33))
    atlas.paste(shift_right(arrow, 2), (255, ROW0_H))

    # red_spike_f1: x=297, y=0, w=59, h=42 — shift 2px up
    spike = base.crop((297, 0, 297 + 59, 42))
    atlas.paste(shift_up(spike, 2), (297, ROW0_H))

    # gold_block_f1: x=487, y=0, w=58, h=39 — shift 1px right + 1px up (gleam bounce)
    gold = base.crop((487, 0, 487 + 58, 39))
    atlas.paste(shift_diag(gold, 1, 1), (487, ROW0_H))

    atlas.save(ATLAS)
    print(f"wrote {ATLAS} {atlas.size}")
    print("  red_arrow_f1  @ (255, 50, 40, 33)  — shift 2px right")
    print("  red_spike_f1  @ (297, 50, 59, 42)  — shift 2px up")
    print("  gold_block_f1 @ (487, 50, 58, 39)  — shift 1px diag (gleam bounce)")


if __name__ == "__main__":
    main()
